project:
  type: website
  output-dir: docs

author: "范翻"
institute: "中央财经大学(CCFD)"

website:
  title: "经济学中的优化方法"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - lecture1.qmd
      - lecture2_lagrange.qmd
      - lecture3_shadow_price.qmd
      - lecture4_value_function.qmd
      - lecture5_convex_set.qmd
      - lecture6_cancave_optimization.qmd
      - lecture7_second_order.qmd
      - lecture8_uncertainty.qmd
      - lecture9_time_related.qmd
  page-navigation: true


format:
  # 网页格式
  html:
    theme: yeti
    css: styles.css
    toc: true
    code-copy: true
    embed-resources: true
  # Beamer幻灯片
  beamer:
    latex-engine: xelatex
    pdf-engine: latexmk  # 启用latexmk引擎
    pdf-engine-opts: 
      - -xelatex         # 指定latexmk使用xelatex
      - -f               # 强制完整编译流程
    template: templates/cufe-red.latex
    documentclass: beamer
    theme: Dresden
    colortheme: seahorse
    fonttheme: professionalfonts
    slide-level: 2
    toc: true
    toc-title: "目录"
execute:
  keep-md: false
  keep-tex: true

editor: visual
