project:
  type: website
  output-dir: docs


website:
  title: "经济学中的优化方法"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于
    right:
      - icon: github
        href: https://github.com/yourrepo
  page-navigation: true

format:
  # 网页格式
  html:
    theme: yeti
    css: styles.css
    toc: true
    code-copy: true
    embed-resources: true
  # Beamer幻灯片
  beamer:
    format: beamer
    output-dir: slides  # Beamer独立输出目录
    keep-md: true
    pdf-engine: xelatex
    slide-level: 2
    # template: templates/beamer-template.tex
    include-in-header:
      text: |
        \usepackage{ctex}
        \usepackage{fontspec}
        \setCJKmainfont{Songti SC}
        \usetheme{Madrid}
        \usecolortheme{dolphin}
execute:
  keep-md: false

editor: visual
