project:
  type: website
  output-dir: docs

author: "范翻"
institute: "中央财经大学(CCFD)"

website:
  title: "经济学中的优化方法"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "第一讲：最优化问题概述"
        href: lecture1_intro.qmd
      - text: "第二讲：拉格朗日方法"
        href: lecture2_lagrange.qmd
      - text: "第三讲：影子价格"
        href: lecture3_shadow_price.qmd
      - text: "第四讲：值函数方法"
        href: lecture4_value_function.qmd
      - text: "第五讲：凸集和线性规划"
        href: lecture5_convex_set.qmd
      - text: "第六讲：凹优化"
        href: lecture6_cancave_optimization.qmd
      - text: "第七讲：二阶条件"
        href: lecture7_second_order.qmd
      - text: "第八讲：不确定性条件下的优化"
        href: lecture8_uncertainty.qmd
      - text: "第九讲：时间相关优化"
        href: lecture9_time_related.qmd
  page-navigation: true


format:
  # 网页格式
  html:
    theme: yeti
    css: styles.css
    toc: true
    code-copy: true
    embed-resources: true
  # Beamer幻灯片
  beamer:
    latex-engine: xelatex
    pdf-engine: latexmk  # 启用latexmk引擎
    pdf-engine-opts: 
      - -xelatex         # 指定latexmk使用xelatex
      - -f               # 强制完整编译流程
    template: templates/cufe-red.latex
    documentclass: beamer
    theme: Dresden
    colortheme: seahorse
    fonttheme: professionalfonts
    slide-level: 2
    toc: true
    toc-title: "目录"
    callout-color: none
execute:
  keep-md: false
  keep-tex: false

editor: visual
