---
subtitle: "第九讲\n时间最大值原理"
editor: visual
---

## 课程导入

> 思考：如果国家要规划未来20年的减排路径，应该怎样平衡短期经济成本和长期环境收益？这与个人的储蓄决策有何异同？

-   政府和居民在当前面临着给定的环境质量（如碳排放水平）；

-   政府需要决定每一期的减排力度，当期环境质量和减排力度决定了下一期的环境质量；

-   社会福利函数会受到每个时期的环境质量影响；

-   减排力度会受到技术水平和当前环境质量的影响；

-   居民会权衡当期和未来的福利，并按照一定方式将未来福利贴现。

## 基础概念

1.  变量区分

| 变量类型 | 符号表示 |     经济学案例     |
|:--------:|:--------:|:------------------:|
| 状态变量 |  $y_t$   | 资本存量、环境质量 |
| 控制变量 |  $z_t$   |  投资额、减排力度  |

2.  动态系统核心方程

$$
y_{t+1} = y_t + Q(y_t,z_t,t)
$$

3.  变量约束方程


$$
G(y_t, z_t, t) \leq 0 \tag{10.2}
$$

> 在碳减排案例中，$Q(\cdot)$函数应该包含哪些关键参数？约束条件$G(\cdot)$可能是什么？

## 基本概念 II

-   目标函数是**加性可分的**，即可以表达成一系列函数的和，且每个函数仅依赖于当期的状态变量和控制变量：
    $$
      \sum_{t = 0}^{T} F(y_{t}, z_{t}, t) \tag{10.3}
    $$

-   可能存在初值条件和终值条件：

    -   初值条件：$y_0 = \bar{y}_0$

    -   终值条件：$y_{T+1} = \bar{y}_{T+1}$

-   **写出上述跨期最大化问题的标准形式。**

## 基本概念 III

一个包含时间维度的最大值问题可以表述为：

$$
\begin{aligned}
    \max_{y_{t}, z_{t}} \quad  &
    \sum_{t = 0}^{T} F(y_{t}, z_{t}, t) \\
    s.t.\quad
         & y_{t+1} - y_{t} = Q(y_{t}, z_{t}, t)     \\
         & G(y_t, z_t, t) \leq 0                    \\
         & y_0 = \bar{y}_0,\quad y_{T+1} = \bar{y}_{T+1} \\
\end{aligned}
$$




## 典型例子：生命周期储蓄 I

考虑一个有已知寿命$T$的工人：

-   其每一期的效用函数为$\ln c_{t}$，$c_{t}$为第$t$期的消费，且效用折现率为$\rho$

-   他可以选择储蓄或借贷，存款利率和贷款利率均为$r$

-   在其生命周期内他将赚取$w$的收入，并用$k_t$表示其在第$t$期积累的资产存量（如果为负则代表债务）

-   资产存量$k_t$会为其带来流量收入$w + rk_t$，因此其资产积累由下式决定
    $$
    k_{t+1} - k_{t} = w + r k_{t} - c_{t}
    $$

-   **写出这个最优化问题的标准形式**，区分状态变量和控制变量。

## 时间最大值问题 I

对于时间最大值问题：

\begin{align}
    \max_{y_{t}, z_{t}} \quad  &
    \sum_{t = 0}^{T} F(y_{t}, z_{t}, t) \\
    s.t.\quad
         & y_{t+1} - y_{t} = Q(y_{t}, z_{t}, t)\tag{10.1} \\
         & G(y_t, z_t, t) \leq 0\tag{10.2}
\end{align}

构造拉格朗日函数，用$\pi_{t+1}$代表约束(10.1)的拉格朗日乘子，$\lambda_{t}$代表约束(10.2)的拉格朗日乘子。

## 时间最大值问题 II

对于拉格朗日函数 $$
\begin{aligned}
    \mathcal{L}(y_{t}, z_{t}, \pi_{t+1}, \lambda_{t})
    =
    \sum_{t = 0}^{T} \{
    & F(y_{t}, z_{t}, t) + \pi_{t+1}[y_{t} + Q(y_{t}, z_{t}, t) - \\
    &   y_{t+1}] - \lambda_{t}G(y_{t}, z_{t}, t)
\}
\end{aligned}
$$

-   $\lambda_{t}$的经济学含义是什么？

    -   关于$t$ 时刻约束的影子价格

-   $\pi_{t+1}$的经济学含义是什么？

    -   关于$t+1$ 时刻存量的影子价格

-   关于$y_{t}$和$z_{t}$的一阶条件分别是什么？

## 一阶条件 I

关于$z_{t}(t = 0, 1, \ldots, T)$的一阶条件：

\begin{align}
\frac{\partial \mathcal{L}}{\partial z_{t}}  \equiv
& F_{z}(y_{t}, z_{t}, t) + \pi_{t+1}Q_z(y_{t}, z_{t}, t) - \\
& \lambda_{t}G_Z(y_{t}, z_{t}, t)  = 0 \tag{10.5}
\end{align}

关于$y_{t}(t = 0, 1, \ldots, T)$的一阶条件，需要将$\mathcal{L}$重新整理为包含所有$y_{t}$的形式：
$$
\begin{aligned}
\mathcal{L}  = & \sum_{t = 0}^{T}
\{
F(y_{t}, z_{t}, t) + \pi_{t+1}Q(y_t, z_t, t) + y_{t}(\pi_{t+1} - \pi_{t}) - \\
& \lambda_{t} G(y_{t}, z_{t}, t)\} +  F(y_0, z_0, 0) + \pi_1 Q(y_0, z_0, 0) + \\
& y_0 \pi_1 - y_{T+1}\pi_{T+1}
\end{aligned}
$$

## 一阶条件 II

因此，关于$y_{t}(t = 0, 1, \ldots, T)$的一阶条件为 $$
\begin{aligned}
\frac{\partial \mathcal{L}}{\partial y_{t}} \equiv &
F_{y}(y_{t}, z_{t}, t) + \pi_{t+1}Q_y(y_{t}, z_{t}, t) + \\
& \pi_{t+1} - \pi_{t} - \lambda_t G_{y}(y_{t}, z_{t}, t) \\
=  & 0
\end{aligned}
$$

或者

\begin{align}
\pi_{t+1}- \pi_{t} & =  -[F_{y}(y_{t}, z_{t}, t) + \pi_{t+1} Q_{y}(y_{t}, z_{t}, t) - \\
& \lambda_{t}G_{y}(y_{t}, z_{t}, t)] \tag{10.8}
\end{align}

## 哈密尔顿函数 I

定义一个新的函数$H$，称为**汉密尔顿函数**： $$
H(y, z, \pi, t) = F(y, z, t) + \pi Q(y, z, t).
$$
考虑一个目标函数是汉密尔顿函数，约束条件服从(10.2)式，选择变量为$z_{t}$的单期最优化问题：
$$
\begin{aligned}
\max_{z_{t}}\quad & F(y_{t}, z_{t}, t) + \pi_{t+1}Q(y_{t}, z_{t}, t) \\
s.t.\quad & G(y_{t}, z_{t}, t) \leq 0
\end{aligned}
$$ **写出上述单期最大化问题的拉格朗日函数。**

## 哈密尔顿函数 II

拉格朗日函数为： $$
L = H(y_{t}, z_{t},\pi_{t+1}, t)  - \lambda_t G(y_{t}, z_{t}, t)
$$ 那么，该拉格朗日函数关于$z_{t}$的一阶条件为： $$
\frac{\partial L}{\partial z_{t}} = F_z + \pi_{t+1}Q_z - \lambda_t G_z = 0
$$
等价于跨期问题的一阶条件(10.5)。当$z_{t}$达到最优时，上述问题的最大值记为$H^{*}(y_{t}, \pi_{t+1}, t)$。

## 哈密尔顿函数 III

在这个框架下，(10.8)可以简写作： $$
\pi_{t+1} - \pi_{t} = - L_{y}(y_{t}, z_{t}, \pi_{t+1}, t)
$$
在静态最大化问题中，只有$z_{t}$是选择变量，$y_{t}$和$\pi_{t+1}$都是参数。因此使用包络定理可得：
$$
\pi_{t+1} - \pi_{t} = - H_{y}^{*}(y_{t}, z_{t}, t) \tag{10.11}
$$ 此外，由包络定理还有
$H_{\pi}^{*} = L_{\pi} = Q$，并在最优解处取值。因此(10.1)式可以写成与(10.11)式对称的形式：
$$
y_{t+1} - y_{t} = H_{\pi}^{*}(y_{t}, \pi_{t+1}, t)
$$

## 最大值原理

最大值原理
在满足约束(10.1)式和(10.2)式下最大化(10.3)式的一阶必要条件是：

-   对每一期的$t$而言, $z_{t}$
    在单期约束$G(y_{t}, z_{t}, t) \leq 0$下最大化汉密尔顿函数$H(y_{t}, z_{t}, \pi_{t+1}, t)$

-   **差分方程**(10.11)式和(10.12)式共同决定了$y_{t}$和$\pi_{t+1}$
    在时间维度上的变动

## 经济学解释 I

最大化条件(i)意味着$z_{t}$的选择会通过(10.1)式影响到$y_{t+1}$，从而影响到$y_{t+1}$和$t+1$时期目标函数中的各项。例如，今天大肆挥霍的消费虽然会增加今天的效用，但意味着未来只有较少的资本积累，从而降低了未来的消费和效用。
如何刻画$z_t$变化对未来的影响？通过利用受影响的存量的影子价格：

-   $z_t$对$y_{t+1}$的影响等于其对$Q(y_t. z_t, t)$的影响

-   由此产生的目标函数值变动等于这一影响乘以$y_{t+1}$的影子价格$\pi_{t+1}$

-   汉密尔顿函数中加入$\pi_{t+1}$修正了目标函数$F(y_{t}, z_{t}, t)$，使之考虑了在$t$时期控制变量$z_{t}$的选择对未来的影响

## 经济学解释 II

\begin{align}
\pi_{t+1} - \pi_{t}
& = -[F_{y}(y_{t}, z_{t}, t) + \pi_{t+1} Q_{y}(y_{t}, z_{t}, t) - \\ & \lambda_{t}G_{y}(y_{t}, z_{t}, t)] \tag{10.8} \\
&  =- H_{y}^{*}(y_{t}, z_{t}, t) \tag{10.11}
\end{align}

(10.8)式或等价的(10.11)式意味着：

-   单期约束的影子成本$\pi_{t+1}$意味着$y_{t}$的一单位边际变化在时期$t$中产生的边际回报为$F_y(t) - \lambda_t G_y(t)$，并在下一期产生额外的$G_y(t)$，即一期中使用$y_{t}$的利息或机会成本

-   当$y_t$为最优解时，全部的边际回报应该为零，即 $$
    [F_y(t) - \lambda_t G_y(t)] + \pi_t Q_y(t) + [\pi_{t+1} - \pi_t] = 0
    $$

## 经济学解释 III

-   对于$y_{T+1}$的终值条件，由于这些存量对于目标函数没有任何贡献，最优策略应该是让$y_{T+1}$尽可能低

-   但在某些情况下，也可以先积累一定存量以提供产出或效用，然后保证其在终值时刻恰好折旧完

-   换言之，我们应该有 $$
    y_{T+1} \geq 0, \quad \pi_{T+1} \geq 0, \text{满足互补松弛条件}
    $$

## 典型例子：生命周期储蓄 II

最大化问题可以写作 $$
\begin{aligned}
\max_{c_t} \quad & \sum_{t = 0}^{T} (1 + \rho)^{-t}\ln(c_t) \\
s.t. \quad & k_{t+1} - k_{t} = w + rk_{t} - c_t
\end{aligned}
$$

定义汉密尔顿函数为 $$
H(k_t, c_t, \pi_{t+1}, t) = (1 + \rho)^{-t} \ln(c_t) + \pi_{t+1}(w + r k_t - c_t)
$$

------------------------------------------------------------------------

## 典型例子：生命周期储蓄 III

使$H$取得最大值的关于$c_t$的条件为： $$
c_t^{-1} (1 + \rho)^{-t} - \pi_{t+1} = 0
$$

汉密尔顿函数的最大值： $$
H^{*} = - [\ln(\pi_{t+1}) + \rho t](1 + \rho)^{-t} + \pi_{t+1}(w + rk_{t}) - (1 + \rho)^{-t}
$$

状态变量差分方程： $$
\begin{aligned}
k_{t+1} - k_{t} & = \frac{\partial H^{*}}{\partial \pi_{t+1}} = w + rk_{t} - \pi_{t+1}^{-1}(1 + \rho)^{-t} \\
\pi_{t+1} - \pi_{t} & = -\frac{\partial H^{*}}{\partial k_{t}} = - r\pi_{t+1}
\end{aligned}
$$

## 典型例子：生命周期储蓄 IV

解得： $$
\pi_{t} = \pi_0 (1 + r)^{-t},\quad c_{t} = \pi_{0}^{-1}\left(\frac{1 + r}{1 + \rho}\right)^t
$$

消费路径特征：

-   当$r > \rho$时，消费持续增长

    -   生命周期早期$c < w$

    -   后期阶段$c > w$

-   当$r < \rho$时，消费呈现递减趋势

## 连续时间模型

将离散时间模型连续化（令$\Delta t \to 0$）： $$
\begin{aligned}
y(t + \delta) - y(t) & = Q(y(t), z(t), t)\delta + o(\delta) \\
\dot{y}(t) & = \lim_{\delta \to 0} \frac{y(t+\delta)-y(t)}{\delta} = Q(y(t), z(t), t)
\end{aligned}
$$

目标函数连续形式： $$
\int_0^T F(y(t), z(t), t) dt
$$
